In [87]:
import numpy as np
import pandas as pd

In [88]:
df = pd.read_csv("listings.csv")

In [89]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,18674,https://www.airbnb.com/rooms/18674,20250914152803,2025-09-15,city scrape,Huge flat for 8 people close to Sagrada Familia,110m2 apartment to rent in Barcelona. Located ...,Apartment in Barcelona located in the heart of...,https://a0.muscache.com/pictures/13031453/413c...,71615,...,4.62,4.82,4.32,ESFCTU000008058000039706000000000000000HUTB-00...,t,26,26,0,0,0.34
1,23197,https://www.airbnb.com/rooms/23197,20250914152803,2025-09-14,city scrape,"Forum CCIB DeLuxe, Spacious, Large Balcony, relax",Beautiful and Spacious Apartment with Large Te...,"Strategically located in the Parc del Fòrum, a...",https://a0.muscache.com/pictures/miso/Hosting-...,90417,...,4.99,4.66,4.68,ESFCTU000008106000547162000000000000000000HUTB...,f,1,1,0,0,0.52
2,32711,https://www.airbnb.com/rooms/32711,20250914152803,2025-09-15,city scrape,Sagrada Familia area - Còrsega 1,A lovely two bedroom apartment only 250 m from...,What's nearby <br />This apartment is located...,https://a0.muscache.com/pictures/357b25e4-f414...,135703,...,4.89,4.89,4.47,HUTB-001722,f,2,2,0,0,0.88
3,34241,https://www.airbnb.com/rooms/34241,20250914152803,2025-09-15,city scrape,Stylish Top Floor Apartment - Ramblas Plaza Real,Located in close proximity to Plaza Real and L...,NaN,https://a0.muscache.com/pictures/2437facc-2fe7...,73163,...,4.68,4.73,4.23,Exempt,f,3,3,0,0,0.14
4,34981,https://www.airbnb.com/rooms/34981,20250914152803,2025-09-15,city scrape,VIDRE HOME PLAZA REAL on LAS RAMBLAS,Spacious apartment for large families or group...,"Located in Ciutat Vella in the Gothic Quarter,...",https://a0.muscache.com/pictures/c4d1723c-e479...,73163,...,4.72,4.65,4.46,ESFCTU000008119000093652000000000000000HUTB-00...,f,3,3,0,0,1.49

In [90]:
df.shape

(19410, 79)

In [91]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19410 entries, 0 to 19409
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            19410 non-null  int64
 1   listing_url                                   19410 non-null  object
 2   scrape_id                                     19410 non-null  int64
 3   last_scraped                                  19410 non-null  object
 4   source                                        19410 non-null  object
 5   name                                          19410 non-null  object
 6   description                                   18673 non-null  object
 7   neighborhood_overview                         8986 non-null   object
 8   picture_url                                   19410 non-null  object
 9   host_id                                       19410 non-null  int64
 10  host_url                                      19410 non-null  object
 11  host_name                                     19405 non-null  object
 12  host_since                                    19405 non-null  object
 13  host_location                                 14708 non-null  object
 14  host_about                                    12240 non-null  object
 15  host_response_time                            16284 non-null  object
 16  host_response_rate                            16284 non-null  object
 17  host_acceptance_rate                          16662 non-null  object
 18  host_is_superhost                             19027 non-null  object
 19  host_thumbnail_url                            19405 non-null  object
 20  host_picture_url                              19405 non-null  object
 21  host_neighbourhood                            8623 non-null   object
 22  host_listings_count                           19405 non-null  float64
 23  host_total_listings_count                     19405 non-null  float64
 24  host_verifications                            19405 non-null  object
 25  host_has_profile_pic                          19405 non-null  object
 26  host_identity_verified                        19405 non-null  object
 27  neighbourhood                                 8986 non-null   object
 28  neighbourhood_cleansed                        19410 non-null  object
 29  neighbourhood_group_cleansed                  19410 non-null  object
 30  latitude                                      19410 non-null  float64
 31  longitude                                     19410 non-null  float64
 32  property_type                                 19410 non-null  object
 33  room_type                                     19410 non-null  object
 34  accommodates                                  19410 non-null  int64
 35  bathrooms                                     15298 non-null  float64
 36  bathrooms_text                                19399 non-null  object
 37  bedrooms                                      17446 non-null  float64
 38  beds                                          15228 non-null  float64
 39  amenities                                     19410 non-null  object
 40  price                                         15276 non-null  object
 41  minimum_nights                                19410 non-null  int64
 42  maximum_nights                                19410 non-null  int64
 43  minimum_minimum_nights                        19406 non-null  float64
 44  maximum_minimum_nights                        19406 non-null  float64
 45  minimum_maximum_nights                        19406 non-null  float64
 46  maximum_maximum_nights                        19406 non-null  float64
 47  minimum_nights_avg_ntm                        19410 non-null  float64
 48  maximum_nights_avg_ntm                        19410 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              18346 non-null  object
 51  availability_30                               19410 non-null  int64
 52  availability_60                               19410 non-null  int64
 53  availability_90                               19410 non-null  int64
 54  availability_365                              19410 non-null  int64
 55  calendar_last_scraped                         19410 non-null  object
 56  number_of_reviews                             19410 non-null  int64
 57  number_of_reviews_ltm                         19410 non-null  int64
 58  number_of_reviews_l30d                        19410 non-null  int64
 59  availability_eoy                              19410 non-null  int64
 60  number_of_reviews_ly                          19410 non-null  int64
 61  estimated_occupancy_l365d                     19410 non-null  int64
 62  estimated_revenue_l365d                       15276 non-null  float64
 63  first_review                                  14421 non-null  object
 64  last_review                                   14421 non-null  object
 65  review_scores_rating                          14421 non-null  float64
 66  review_scores_accuracy                        14418 non-null  float64
 67  review_scores_cleanliness                     14419 non-null  float64
 68  review_scores_checkin                         14417 non-null  float64
 69  review_scores_communication                   14420 non-null  float64
 70  review_scores_location                        14418 non-null  float64
 71  review_scores_value                           14418 non-null  float64
 72  license                                       13930 non-null  object
 73  instant_bookable                              19410 non-null  object
 74  calculated_host_listings_count                19410 non-null  int64
 75  calculated_host_listings_count_entire_homes   19410 non-null  int64
 76  calculated_host_listings_count_private_rooms  19410 non-null  int64
 77  calculated_host_listings_count_shared_rooms   19410 non-null  int64
 78  reviews_per_month                             14421 non-null  float64
dtypes: float64(23), int64(20), object(36)
memory usage: 11.7+ MB

In [93]:
df.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,1.941000e+04,1.941000e+04,1.941000e+04,19405.000000,19405.000000,19410.000000,19410.000000,19410.000000,15298.000000,17446.000000,...,14419.000000,14417.000000,14420.000000,14418.000000,14418.000000,19410.000000,19410.000000,19410.000000,19410.000000,14421.000000
mean,6.210978e+17,2.025091e+13,2.116496e+08,83.327648,110.233600,41.392248,2.166968,3.406079,1.429958,1.855784,...,4.612500,4.711266,4.707282,4.746362,4.450876,61.671716,44.467336,17.068830,0.097063,1.492801
std,5.893311e+17,5.879058e+00,2.147334e+08,178.410903,224.294018,0.014031,0.017689,2.324706,0.822785,1.376608,...,0.520479,0.495905,0.517222,0.397999,0.581650,122.900150,108.333156,67.119687,0.710256,2.213720
min,1.867400e+04,2.025091e+13,3.073000e+03,1.000000,1.000000,41.351783,2.085593,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,3.048967e+07,2.025091e+13,1.343129e+07,2.000000,3.000000,41.381170,2.156510,2.000000,1.000000,1.000000,...,4.500000,4.670000,4.670000,4.680000,4.320000,2.000000,0.000000,0.000000,0.000000,0.210000
50%,7.056056e+17,2.025091e+13,1.390639e+08,9.000000,13.000000,41.390054,2.167765,3.000000,1.000000,1.000000,...,4.750000,4.860000,4.860000,4.850000,4.570000,7.000000,3.000000,0.000000,0.000000,0.820000
75%,1.181663e+18,2.025091e+13,3.678971e+08,47.000000,78.000000,41.401569,2.177668,4.000000,2.000000,2.000000,...,4.940000,5.000000,5.000000,5.000000,4.780000,40.000000,23.000000,2.000000,0.000000,2.220000
max,1.509435e+18,2.025091e+13,7.186126e+08,994.000000,2706.000000,41.462243,2.221830,16.000000,14.000000,29.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,514.000000,514.000000,417.000000,12.000000,94.770000

In [94]:
df_model = df[[
    'price',
    'room_type',
    'bedrooms',
    'bathrooms',
    'beds']]

In [96]:
df_model = df_model.dropna()

In [97]:
df_model = pd.get_dummies(df_model, drop_first=True)

In [98]:
df_model['price'] = df_model['price'].replace('[\$,]', '', regex=True).astype(float)

In [99]:
df_model['price'].dtype

dtype('float64')

In [100]:
df_model.head()

,price,bedrooms,bathrooms,beds,room_type_Hotel room,room_type_Private room,room_type_Shared room
0,210.0,3.0,2.0,6.0,False,False,False
1,285.0,3.0,2.0,4.0,False,False,False
2,170.0,2.0,1.5,3.0,False,False,False
3,110.0,1.0,1.0,1.0,False,False,False
4,333.0,4.0,3.0,6.0,False,False,False

In [101]:
df_model.isnull().sum().sum()

np.int64(0)

In [102]:
X = df_model.drop('price', axis=1)
y = df_model['price']

In [103]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [104]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [105]:
y_pred = model.predict(X_test)

In [107]:
from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("R2 :", r2)

MAE : 106.04754597632348
R2 : 0.09104564254114522

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

from sklearn.metrics import mean_absolute_error, r2_score

print("MAE :", mean_absolute_error(y_test, y_pred_rf))
print("R2 :", r2_score(y_test, y_pred_rf))

## Modélisation

Un modèle de régression linéaire et un modèle Random Forest ont été testés pour prédire le prix des logements.

Le modèle Random Forest donne de meilleurs résultats avec une erreur moyenne d’environ 95€, mais les performances restent limitées (R² ≈ 0.11).

Cela s’explique par la complexité du prix des logements Airbnb et le manque de certaines variables importantes.